import customerRoutes from './customerRoutes';
import authRoutes from './authRoutes';
import bookingRoutes from './bookingRoutes';
import queryRoutes from './queryRoutes';
import paymentRoutes from './paymentRoutes';
import ownerRoutes from './ownerRoutes';
import agentRoutes from './agentRoutes';
import superAgentRoutes from './superAgentRoutes';
import adminRoutes from './adminRoutes';
export { customerRoutes, ownerRoutes, authRoutes, bookingRoutes, queryRoutes,paymentRoutes,agentRoutes,superAgentRoutes,adminRoutes };
